version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootPass
      MYSQL_DATABASE: simple
    ports:
      - "3307:3306"
    volumes:
      - ~/simple_db:/var/lib/mysql

  app:
    build:
      context: .
    restart: always
    ports:
      - 8091:8091
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url":"jdbc:mysql://db:3306/simple?useSSL=false",
              "spring.datasource.username":"root",
              "spring.datasource.password":"rootPass",
              "server.port":8091,
              "spring.datasource.driver-class-name":"com.mysql.cj.jdbc.Driver",
              "spring.liquibase.change-log":"classpath:/liquibase/master.xml",
              "simple.openapi.dev-url":"http://localhost:8091",
              "simple.openapi.homolog-url":"http://simple-homolog.qualquercoisa.com.br",
              "simple.openapi.prod-url":"https://simple.qualquercoisa.com.br",
              "spring.main.allow-bean-definition-overriding":"true",
              "management.endpoints.web.exposure.include":"*",
              "management.endpoint.health.show-details":"always",
              "management.health.circuitbreakers.enabled":true,
              "management.health.ratelimiters.enabled":true,
              "resilience4j.circuitbreaker.instances.default.failure-rate-threshold":50,
              "resilience4j.circuitbreaker.instances.default.minimum-number-of-calls":10,
              "resilience4j.circuitbreaker.instances.default.automatic-transition-from-open-to-half-open-enabled":true,
              "resilience4j.circuitbreaker.instances.default.wait-duration-in-open-state":"15s",
              "resilience4j.circuitbreaker.instances.default.permitted-number-of-calls-in-half-open-state":3,
              "resilience4j.circuitbreaker.instances.default.sliding-window-size":10,
              "resilience4j.circuitbreaker.instances.default.sliding-window-type":"count_based",
              "resilience4j.retry.instances.default.max-attempts":3,
              "resilience4j.retry.instances.default.wait-duration":"1s",
              "resilience4j.retry.metrics.legacy.enabled":true,
              "resilience4j.retry.metrics.enabled":true,
              "resilience4j.retry.instances.default.enable-exponential-backoff":true,
              "resilience4j.retry.instances.default.exponential-backoff-multiplier":2,
              "simple.professionalId":1
            }'
    volumes:
      - ~/m2_compose:/root/.m2
    depends_on:
      - simple