version: '3.1'
services:
  db:
    image: mysql:5.7
    restart: always
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootPass
      MYSQL_DATABASE: simple
    ports:
      - "3307:3306"
    volumes:
      - ~/db_simple:/var/lib/mysql

# Names our volume
volumes:
  my-db:
